version: "3"
services:

  web:
    image: php:7.3.6-apache-stretch
    command: apt-get update && apt-get install -y php-mysql
    ports:
      - "8080:80"
    networks:
      - frontend
    volumes:
      - ./code:/var/www/html:ro
  db:
    - image: mariadb:10.4.5-bionic
    - expose:
       - 3306
    networks:
      - frontend
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-letmein} 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
    volumes:
      - ~/maria-db:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d



networks: 
  frontend: